// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_all_chirps_from_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAllChirpsFromUser = `-- name: GetAllChirpsFromUser :many
select id, created_at, updated_at, body, user_id from chirps
where id = $1 or $2 = TRUE
order by created_at asc
`

type GetAllChirpsFromUserParams struct {
	ID      uuid.UUID
	Column2 interface{}
}

func (q *Queries) GetAllChirpsFromUser(ctx context.Context, arg GetAllChirpsFromUserParams) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getAllChirpsFromUser, arg.ID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
