// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_user_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserRed = `-- name: UpdateUserRed :one
update users
set
    is_red = true,
    updated_at = now()
where id = $1
returning id, created_at, updated_at, email, hashed_password, is_red
`

func (q *Queries) UpdateUserRed(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRed, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsRed,
	)
	return i, err
}
